function [ curva ] = createCurve( bonds )
%CREATECURVE Summary of this function goes here
%   Detailed explanation goes here

% strumenti={'Bond';'Bond';'Bond';'Bond';'Bond'};
% prezzi = [100.48; 105.37; 108.14; 114.48; 108.83];
% 
% sett = [datenum('20-Nov-2017'),...
%         datenum('20-Nov-2017'),...
%         datenum('20-Nov-2017'),...
%         datenum('20-Nov-2017'),...
%         datenum('20-Nov-2017')];
% 
% matu = [datenum('4-Jan-2022'),...
%         datenum('4-Jul-2023'),...
%         datenum('4-Jul-2025'),...
%         datenum('4-Jul-2018'),...
%         datenum('4-Jan-2020')];
%     
% cedole = [0.05; 0.0375; 0.0325; 0.0425; 0.0325];
%     
% btp=struct('name',{strumenti},...
%            'price',prezzi,...
%            'maturity',{matu},...
%            'coupon',cedole,...
%            'date',sett);
% 
% %questi dati permettono di costruire la curva dei tassi con la funzione
% %IRDataCurve.bootstrap
% 
curva = IRDataCurve.bootstrap('Zero',btp.date(1,1),btp.name, ...
    [btp.date' btp.maturity' btp.price],...
    'InstrumentCouponRate',btp.coupon);

end

